demo:
  build: .
  restart: always
  ports:
    - '3000'
  labels:
    - traefik.backend=nuxt
    - traefik.frontend.rule=Host:nuxt.mrossignol.fr
    - traefik.port=3000
    - traefik.frontend.entryPoints=http,https
